Class {
	#name : 'MAActionPragmaBuilder',
	#superclass : 'MAPragmaBuilder',
	#category : 'Magritte-Model-Utility',
	#package : 'Magritte-Model',
	#tag : 'Utility'
}

{ #category : 'constants' }
MAActionPragmaBuilder class >> magritteDescriptionExtensionPragma [ 
	^ #magritteActionDescription:
]

{ #category : 'constants' }
MAActionPragmaBuilder class >> magritteDescriptionPragma [ 
	^ #magritteActionDescription
]
